apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlops-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2025-09-06T17:39:05.553135',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "kubeflow testing pipeline.",
      "name": "MLOPS pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: mlops-pipeline
  templates:
  - name: data-processing
    container:
      command: [python, src/data_processing.py]
      image: ay2728850/corectal-prediction:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: mlops-pipeline
    dag:
      tasks:
      - {name: data-processing, template: data-processing}
      - name: model-training
        template: model-training
        dependencies: [data-processing]
  - name: model-training
    container:
      command: [python, src/model_training.py]
      image: ay2728850/corectal-prediction:latest
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
